name: lastandfinal
description: "A new Flutter project."
publish_to: 'none' # This line prevents the package from being published to pub.dev. Remove it if you want to publish it.

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # Specify a range for compatibility.

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8 # Dependency for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Linting rules for your code.

flutter:
  uses-material-design: true # Ensures Material Design icons are available.

  assets:
    - assets/map_background.png # Correctly list assets you want to include.

  # Optional: Include fonts if you have custom ones.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
